### ISSUE TITLE
Should "tilda_tools sync" only sync bootstrapped apps?

### ISSUE THREAD

**Issue by SteveAmor** [emfcamp/Mk4-Apps#123]
There are a lot of apps now.  If you clone the repo and do a `./tilda_tools sync` you sync all off the apps, including the ones that have `___bootstrap___ = False`.  This is going to take up a lot of space on the flash and will eventually fill it up completely.

**Comment by mstratford** [comment]
Can confirm it is now taking ages to tilda_tools sync because of this...
