### ISSUE TITLE
mass storage doesn't unmount cleanly from ubuntu 16.04 MATE desktop 1.12.1

### ISSUE THREAD

**Issue by tatzelbrumm** [emfcamp/Mk4-Apps#143]
Under ubuntu 16.04 with MATE desktop 1.12.1, I can access the mass storage and write files, 
but when I unmount, the badge resets itself to the default file system (without my changes), and the mass storage device throws an I/O error at subsequent attempts to access the mass storage.

**Comment by SteveAmor** [comment]
Duplicate of #45
Please can you close this issue.

**Comment by tatzelbrumm** [comment]
This is indeed a duplicate of [https://github.com/emfcamp/Mk4-Apps/issues/45](#45).
