### ISSUE TITLE
On site Thursday evening sprint

### ISSUE THREAD

**Issue by SteveAmor** [emfcamp/Mk4-Apps#26]
Will there be a Thursday evening sprint to work through as many issues as possible?

**Comment by marekventur** [comment]
I assume we're going to be quite busy tonight, so yes. When you arrive on side please make sure you get wrist-banded and find us in the badge tent https://map.emfcamp.org/#18/52.040645/-2.378056.

There is a chance that we will have to jump in and help with other stuff around the site on short notice though, so come equipped for all likelihoods.
