### ISSUE TITLE
SerialTimeoutException from tilda_tools whatever I attempt 

### ISSUE THREAD

**Issue by wdoekes** [emfcamp/Mk4-Apps#47]
Hi,
```
$ sudo ./tilda_tools test
Local Test: PASS
Connected to badge: DONE
Stopping running app:Traceback (most recent call last):
  File "./tilda_tools", line 153, in <module>
    main()
  File "./tilda_tools", line 117, in main
    pyboard_util.stop_badge(args, args.verbose)
  File "/home/walter/srcelf/Mk4-Apps/.development/pyboard_util.py", line 31, in stop_badge
    write_command(pyb, b'\r\x03\x03') # ctrl-C twice: interrupt any running program
  File "/home/walter/srcelf/Mk4-Apps/.development/pyboard_util.py", line 40, in write_command
    pyb.serial.write(command)
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 552, in write
    raise writeTimeoutError
serial.serialutil.SerialTimeoutException: Write timeout
```
Whatever I do, I get the serialtimeout. Decreasing baud rate to 14400 or lower doesn't help.

I don't have any affinity with COM/USB ports, so this is all black magic to me thusfar.

Any ideas or tips?

**Comment by marksbrown** [comment]
I had this. I installed the mass storage app, connected and manually copied snake across. Whilst running that I ran the tests again. Seemingly worked then oddly enough.

**Comment by fooforever** [comment]
Managed to get rid of this error using the updated proves on the wiki. Connect with minicom, reset the badge whilst mashing ctrl-c in minicom, ctrl-a x to exit minicom then download the app using Tilda tools.

**Comment by wdoekes** [comment]
Thanks for the replies!

Yes. Running minicom, bashing ctrl-c and hitting reset on the device did the trick :ok_hand:

(Closing.)
