### ISSUE TITLE
Can we have a "Hello World" main.py to place in root please

### ISSUE THREAD

**Issue by SteveAmor** [emfcamp/Mk4-Apps#48]
I just can't get any of my main.py programs to work, even a simple:

```
print("Hello World")
```

Assuming that prints to the serial port.

**Comment by bboortz** [comment]
Hi,
I have just created a pull request: https://github.com/emfcamp/Mk4-Apps/pull/56. Hope that meet your requirement.

**Comment by SteveAmor** [comment]
Thanks @bboortz
