### ISSUE TITLE
Device hangs if it tries to update an app that is already removed from badge store

### ISSUE THREAD

**Issue by bboortz** [emfcamp/Mk4-Apps#57]
In case you have installed an app that has been removed from badge store in the meantime, you are unable to update the device. 
It seems that the update procedure is iterating over all installed apps. If it tries to update the removed app the devices hangs

how to simulate?
Badge Store -> Update all Apps

**Comment by Pezmc** [comment]
This currently means I (and many others), can't install any apps from the app store, since we've manually sent apps down a USB cable. We were seeing a white screen after installing.
