### ISSUE TITLE
Stuck in a loop

### ISSUE THREAD

**Issue by adnathanail** [emfcamp/Mk4-Apps#63]
### Hi, I'm stuck in a loop:
My badge was working but I couldn't connect to it over serial (Separate issue I think) so I reset it and now when I boot the badge I get a message saying `Long Press MENU` so I do (and nothing else does anything).
When I do this the badge resets and then I get a screen saying `Select App to start`; if I select home_default then it goes back to `Long Press MENU`. If I select launcher then it goes straight back to `Select App to start`. If I select any other app then it reboots and takes me to the app but if I try and go to the menu then I get back to `Long Press MENU` and I am stuck again!
I'm probably being stupid but any help would be greatly appreciated

**Comment by adnathanail** [comment]
Oh wow please delete this I have realised this is how the menu is supposed to work I'm so sorry for wasting peoples time

**Comment by SteveAmor** [comment]
@adnathanail can you close this issue.  Thanks.
