### ISSUE TITLE
Random is very non random

### ISSUE THREAD

**Issue by Pezmc** [emfcamp/Mk4-Apps#76]
For an example, try snake, the X&Y coordinates of the food is always the same, forming a diagonal line.

**Comment by wdoekes** [comment]
Hehe, yea, I noticed this as well when trying out a simple print-my-name-on-a-random-location app.

**Comment by SteveAmor** [comment]
There appears to be no entropy.  I wonder if it can be seeded with the current time (or time since boot up)?
